
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: E_com_app_development
  username: s-hashmi
  password: 7832

test:
  <<: *default
  database: E_com_app_test

production:
  <<: *default
  database: E_com_app_production